### ISSUE TITLE
Need update (V6.0.0.3)

### ISSUE THREAD

**Issue by OliverTrust** [chr233/ASFAchievementManagerEx#3]
```
Method 'OnASFInit' in type 'ASFAchievementManagerEx.ASFAchievementManagerEx' from assembly 'ASFAchievementManagerEx, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at ArchiSteamFarm.Plugins.PluginsCore.InitPlugins()
System.TypeLoadException: Method 'OnASFInit' in type 'ASFAchievementManagerEx.ASFAchievementManagerEx' from assembly 'ASFAchievementManagerEx, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by chr233** [comment]
i am in the hosptial now, not able to coding right now

i have an operation tomorrow, and have to laying on bed for serival days

**Comment by chr233** [comment]
> i am in the hosptial now, not able to coding right now
> 
> i have an operation tomorrow, and have to laying on bed for serival days

![IMG_20240310_150459.jpg](https://github.com/chr233/ASFAchievementManagerEx/assets/13798576/8a4fccba-412b-4da7-a975-3fff0036e527)

**Comment by OliverTrust** [comment]
Get well soon!)

**Comment by chr233** [comment]
> Get well soon!)

tkx

**Comment by OliverTrust** [comment]
need update

**Comment by chr233** [comment]
> need update

got it
